# Generated by Django 4.1.4 on 2022-12-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Driving_License', models.IntegerField()),
                ('Region_Code', models.FloatField()),
                ('Previously_Insured', models.IntegerField()),
                ('Vehicle_Age', models.IntegerField()),
                ('Vehicle_Damage', models.CharField(max_length=10)),
                ('Annual_Premium', models.IntegerField()),
                ('Policy_Sales_Channel', models.IntegerField()),
                ('Vintage', models.IntegerField()),
                ('Response', models.IntegerField()),
            ],
        ),
    ]
