# Generated by Django 4.1.4 on 2022-12-21 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='BirthDate',
        ),
        migrations.AddField(
            model_name='customer',
            name='BirthDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 21, 0, 37, 7, 437259)),
        ),
        migrations.AddField(
            model_name='customer',
            name='Name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Annual_Premium',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Driving_License',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Policy_Sales_Channel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Previously_Insured',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Region_Code',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Response',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Vehicle_Age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Vehicle_Damage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Vintage',
            field=models.IntegerField(blank=True),
        ),
    ]
