# Generated by Django 4.1.4 on 2022-12-21 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0003_remove_person_birthdate_customer_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Response',
        ),
        migrations.AlterField(
            model_name='customer',
            name='BirthDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 21, 0, 39, 35, 537700)),
        ),
    ]
