# Generated by Django 4.1.4 on 2022-12-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0005_alter_customer_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Annual_Premium',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
