# Generated by Django 4.0.4 on 2022-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0006_alter_customer_annual_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Driving_License',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Previously_Insured',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
